service:
  service_name: "data-processing-service"
  service_port: 8002

external:
  user_service:
    base_url: "https://unhook-1aci.onrender.com"
    port: 443
    timeout: 120.0  # 2 minutes timeout
