service:
  service_name: "data_processing_service"
  service_port: 443

external:
  user_service:
    base_url: "https://unhook-production-0e0c.up.railway.app"
    port: 443
    timeout: 120.0 # 2 minutes timeout

redis:
  host: "redis"
  port: 6379
  db: 0

s3:
  account_id: "3a16fd5fe268c9357783c8e2a1ecf1e2"
  bucket_name: "unhook-ephemeral"
  endpoint_url: "https://3a16fd5fe268c9357783c8e2a1ecf1e2.r2.cloudflarestorage.com"
