service:
  service_name: "data-collector-service"
  service_port: 8001

external:
  user_service:
    base_url: "https://unhook-1aci.onrender.com"
    port: 443
    timeout: 120.0  # 2 minutes timeout

proxy:
  base_url: "api.zyte.com:8011"
