service:
  service_name: "data_collector_service"
  service_port: 8001

external:
  user_service:
    base_url: "http://user_service"
    port: 8000
    timeout: 120.0 # 2 minutes timeout

proxy:
  base_url: "api.zyte.com:8011"

redis:
  host: "redis"
  port: 6379
  db: 0
