service:
  service_name: "data-collector-service"
  service_port: 8001

external:
  user_service:
    base_url: "https://unhook-production-0e0c.up.railway.app"
    port: 443
    timeout: 120.0 # 2 minutes timeout

proxy:
  base_url: "api.zyte.com:8011"

redis:
  host: "redis"
  port: 6379
  db: 0

messaging:
  command_topic: "data_collector.commands"
