name: Scheduled Newspaper Processing

on:
  schedule:
    # 12 PM and 5 PM UK local time (BST is UTC+1)
    - cron: "0 11,16 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-newspaper-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Newspaper Processing for User 1
        run: |
          curl --fail --location --request POST --retry 3 --retry-delay 2 --retry-all-errors 'https://unhook-production-b172.up.railway.app/internal/process_newspaper_for_user/607d95f0-47ef-444c-89d2-d05f257d1265'

      - name: Trigger Newspaper Processing for User 2
        run: |
          curl --fail --location --request POST --retry 3 --retry-delay 2 --retry-all-errors 'https://unhook-production-b172.up.railway.app/internal/process_newspaper_for_user/91f21ebd-73bb-49b0-82cf-a78dae3caebd'
